<?php 
	unset($_SESSION['check']);
	unset($_SESSION['ch']);
	unset($_SESSION['pr1']);
	unset($_SESSION['pr2']);
	unset($_SESSION['pr_ofc']);
	unset($_SESSION['curr_ofc']);
	unset($_SESSION['curr_ord']);
?>